const { admin, db } = require('../config/firebaseConfig');
const axios = require('axios');

exports.registerUser = async (userData) => {
    const { email, password, name, phone, role } = userData;

    // STEP 1: Create User in Firebase Authentication
    // This handles password hashing automatically.
    const userRecord = await admin.auth().createUser({
        email: email,
        password: password,
        displayName: name
    });

    // The unique ID generated by Firebase
    const uid = userRecord.uid;

    // STEP 2: Prepare data for Firestore Database
    const userDoc = {
        uid: uid,
        email: email,
        name: name,
        phone: phone || "",
        role: role || "RIDER", // Default to Rider if not specified
        createdAt: new Date().toISOString(),
        isVerified: false
    };

    // STEP 3: Save to Firestore 'users' collection
    // We use .set() with the specific UID so Auth and DB match perfectly
    await db.collection('users').doc(uid).set(userDoc);

    // Return the clean data (excluding the password)
    return userDoc;
};

exports.loginUser = async (email, password) => {
    // STEP 1: Verify Password with Firebase Auth (REST API)
    // We use the Identity Toolkit API because Admin SDK cannot "Sign In"
    const apiKey = process.env.FIREBASE_WEB_API_KEY;
    const verifyUrl = `https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${apiKey}`;

    let firebaseUid;

    try {
        const response = await axios.post(verifyUrl, {
            email: email,
            password: password,
            returnSecureToken: true
        });
        
        // If successful, Firebase returns the localId (UID)
        firebaseUid = response.data.localId;

    } catch (error) {
        // If axios fails (wrong password), throw a specific error
        console.error("Firebase Auth Error:", error.response?.data?.error?.message);
        throw new Error("INVALID_LOGIN");
    }

    // STEP 2: Fetch extra details from YOUR Firestore Database
    // (Because Firebase Auth only knows email/password, not 'Role' or 'Name')
    const userDoc = await db.collection('users').doc(firebaseUid).get();

    if (!userDoc.exists) {
        throw new Error("User found in Auth but not in Database (Data inconsistency)");
    }

    // STEP 3: Return the combined data
    return userDoc.data();
};